name: cometdev
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ad_gridview: ^0.0.5
  advanced_search: ^2.2.4
  animated_notch_bottom_bar: ^1.0.3
  animated_toggle_switch: ^0.8.2
  awesome_bottom_bar: ^1.2.4
  bottom_bar_matu: ^1.5.0
  bottom_navbar_with_indicator: ^0.0.9
  carousel_slider: ^4.2.1
  date_format_field: ^0.1.0
  dob_input_field: ^2.0.0
  dot_curved_bottom_nav: ^0.0.2
  fast_validator: ^0.2.0
  fluid_bottom_nav_bar: ^1.4.0
  flutter:
    sdk: flutter
  flutter_google_places_hoc081098: ^2.0.0-beta.1
  flutter_otp_text_field: ^1.1.3+2
  flutterotpfield: ^0.0.3
  footer: ^0.0.4
  gender_picker: ^1.1.0
  geolocator: ^12.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.2.8
  hexcolor: ^3.0.1
  horizontal_list: ^0.0.7
  http: ^1.2.2
  intl_phone_field: ^3.2.0
  intl_phone_number_field: ^0.2.0
  lite_rolling_switch: ^1.0.1
  location: ^6.0.2
  persistent_bottom_nav_bar_v2: ^5.3.0
  pin_code_fields: ^8.0.1
  pinput: ^5.0.0
  responsive_builder: ^0.7.1
  responsive_framework: ^1.4.0
  rolling_switch: ^0.0.2
  simple_form_validations: ^1.0.1
  sliding_clipped_nav_bar: ^3.1.1
  switch_button: ^0.0.1
  switcher_button: ^0.0.4
  theme_button: ^1.0.4
  water_drop_nav_bar: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/v.png
    - assets/comet.png
    - assets/tavatar.png
    - assets/hs/
    - assets/bb/
    - assets/ss/
    - assets/carousel/
    - assets/profile/
    - assets/brands/
    - assets/listview1.jpeg
    - assets/listview2.jpeg
    - assets/listview3.jpeg
    - assets/trancard1.png
    - assets/cometintro.png
    - assets/fashion/
    - assets/haircare/
    - assets/food/
    - assets/skincare/
    - assets/tranpage/
